export const seedMenuItems = [
  // COFFEE
  {
    name: 'Single Origin Espresso',
    description: 'Double shot extracted from high-elevation Ethiopian Yirgacheffe heirloom beans. Bright notes of bergamot, jasmine, and citrus zest.',
    price: 160,
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&w=800&q=80',
    isFeatured: true,
    tags: ['Single Origin', 'House Special'],
    brewMethod: '9-Bar Precision Pull',
    calories: 5,
    origin: 'Yirgacheffe, Ethiopia (2,100m)',
  },
  {
    name: 'Velvet Flat White',
    description: 'Ristretto double shot paired with silky microfoam steamed to exactly 65°C. Rich caramel body with a velvety mouthfeel.',
    price: 220,
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1577968897966-3d4325b36b61?auto=format&fit=crop&w=800&q=80',
    isFeatured: true,
    tags: ['Barista Pick'],
    brewMethod: 'Ristretto & Microfoam',
    calories: 130,
    origin: 'Chikmagalur Estate, Karnataka',
  },
  {
    name: 'Artisan Spanish Latte',
    description: 'Full-bodied espresso infused with slow-reduced condensed milk and organic whole milk, dusted with hand-ground cinnamon bark.',
    price: 240,
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&w=800&q=80',
    isFeatured: true,
    tags: ['Signature Drink'],
    brewMethod: 'Layered Espresso Pull',
    calories: 210,
    origin: 'Coorg Special Roast, India',
  },
  {
    name: 'Slow Drip Cold Brew',
    description: 'Steeped cold for 22 hours through unbleached paper filters. Ultra-smooth, zero bitterness, with undertones of dark cocoa and black cherry.',
    price: 210,
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=800&q=80',
    isFeatured: false,
    tags: ['22-Hour Steep', 'Low Acidity'],
    brewMethod: 'Kyoto Drip Tower',
    calories: 10,
    origin: 'Huila, Colombia',
  },
  {
    name: 'Classic Americano',
    description: 'Two shots of rich espresso poured over crystal mountain spring water. Pure, clean roasted hazelnut notes.',
    price: 180,
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    isFeatured: false,
    tags: ['Classic', 'Organic'],
    brewMethod: 'Espresso Long Pour',
    calories: 5,
    origin: 'Araku Valley, Andhra Pradesh',
  },
  {
    name: 'Roasted Hazelnut Cappuccino',
    description: 'Equal thirds of bold espresso, steamed cream, and dense velvety dry foam, finished with roasted Piedmont hazelnut crumb.',
    price: 230,
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=800&q=80',
    isFeatured: false,
    tags: ['Comfort Craft'],
    brewMethod: 'Traditional 1:1:1 Ratio',
    calories: 150,
    origin: 'Chikmagalur & Java Blend',
  },
  {
    name: 'Valrhona Café Mocha',
    description: 'Rich double espresso swirled with melted 70% Valrhona dark chocolate, steamed jersey milk, and a delicate touch of sea salt.',
    price: 250,
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?auto=format&fit=crop&w=800&q=80',
    isFeatured: false,
    tags: ['Valrhona Chocolate'],
    brewMethod: 'Espresso Ganache Infusion',
    calories: 260,
    origin: 'Chikmagalur Estate + Guanaja Cacao',
  },
  {
    name: 'Spanish Cortado',
    description: 'Equal parts bold ristretto and warm textured milk served in a faceted Gibraltar glass to cut the acidity while elevating sweetness.',
    price: 190,
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1585494156145-1c60a4fe9d2b?auto=format&fit=crop&w=800&q=80',
    isFeatured: false,
    tags: ['Gibraltar Cut'],
    brewMethod: 'Ristretto Cut',
    calories: 70,
    origin: 'Tarrazú, Costa Rica',
  },

  // NON-COFFEE
  {
    name: 'Ceremonial Uji Matcha Latte',
    description: 'First-harvest ceremonial grade stone-ground matcha from Uji, Kyoto, whisked with bamboo chasen and folded into silky oat milk.',
    price: 260,
    category: 'non-coffee',
    image: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=800&q=80',
    isFeatured: true,
    tags: ['Ceremonial Grade', 'Uji Kyoto', 'Oat Milk'],
    brewMethod: 'Traditional Chasen Whisk',
    calories: 120,
    origin: 'Uji, Kyoto, Japan',
  },
  {
    name: 'Single Origin Hot Chocolate',
    description: 'Pure 72% single-origin Madagascar cacao melted into organic whole milk, infused with genuine vanilla bean and toasted cinnamon.',
    price: 240,
    category: 'non-coffee',
    image: 'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?auto=format&fit=crop&w=800&q=80',
    isFeatured: false,
    tags: ['Madagascar 72%', 'Decadent'],
    brewMethod: 'Slow Melt Pot',
    calories: 280,
    origin: 'Sambirano Valley, Madagascar',
  },
  {
    name: 'Himalayan Spiced Chai Latte',
    description: 'Hand-crushed green cardamom, cinnamon quills, ginger root, and cloves simmered with organic CTC black tea and fresh mountain milk.',
    price: 200,
    category: 'non-coffee',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80',
    isFeatured: false,
    tags: ['House Spice Blend', 'Himachal Sourced'],
    brewMethod: 'Slow Decoction',
    calories: 140,
    origin: 'Kangra Valley, Himachal Pradesh',
  },
  {
    name: 'Sparkling Hibiscus Rose Tea',
    description: 'Cold-steeped organic wild hibiscus petals, crushed Persian rosebuds, fresh lime, and botanical sparkling water over hand-cut ice.',
    price: 210,
    category: 'non-coffee',
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=800&q=80',
    isFeatured: false,
    tags: ['Refreshing', 'Botanical', 'Vegan'],
    brewMethod: 'Cold Maceration',
    calories: 45,
    origin: 'Organic Wild Flora',
  },

  // BAKERY
  {
    name: 'Truffle & Wild Mushroom Croissant',
    description: 'Laminated with cultured French butter for 72 layers, stuffed with slow-braised Himalayan morels, aged Gruyère, and white truffle oil.',
    price: 280,
    category: 'bakery',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=80',
    isFeatured: true,
    tags: ['Chef Special', '72 Layers'],
    brewMethod: 'Baked Fresh Hourly',
    calories: 340,
    origin: 'Artisan Oven, In-House',
  },
  {
    name: 'Flaky French Butter Croissant',
    description: 'Golden honeycomb interior with an audibly crisp shell, crafted solely with AOP Charentes-Poitou cultured French butter.',
    price: 190,
    category: 'bakery',
    image: 'https://images.unsplash.com/photo-1549903072-7e6e0bedb7fb?auto=format&fit=crop&w=800&q=80',
    isFeatured: false,
    tags: ['AOP French Butter', 'Crisp'],
    brewMethod: 'Slow Fermented 48h',
    calories: 290,
    origin: 'Artisan Oven, In-House',
  },
  {
    name: 'Twice-Baked Almond Croissant',
    description: 'Filled with rich Tahitian vanilla frangipane almond cream, soaked in orange blossom syrup, and coated in toasted sliced almonds.',
    price: 240,
    category: 'bakery',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
    isFeatured: false,
    tags: ['Almond Frangipane'],
    brewMethod: 'Twice Baked',
    calories: 380,
    origin: 'Artisan Oven, In-House',
  },
  {
    name: 'Cardamom Brown Butter Cinnamon Roll',
    description: 'Pillow-soft enriched brioche rolled with freshly cracked green cardamom, Ceylon cinnamon, and glazed with cream cheese vanilla bean frosting.',
    price: 220,
    category: 'bakery',
    image: 'https://images.unsplash.com/photo-1509365465985-25d11c17e812?auto=format&fit=crop&w=800&q=80',
    isFeatured: false,
    tags: ['Brown Butter Glaze', 'Brioche'],
    brewMethod: 'Brioche Slow Proof',
    calories: 390,
    origin: 'Artisan Oven, In-House',
  },
  {
    name: 'Pain au Chocolat',
    description: 'Flaky laminated pastry encasing two batons of Valrhona 64% dark chocolate, baked until glossy and delicately crisp.',
    price: 210,
    category: 'bakery',
    image: 'https://images.unsplash.com/photo-1608198093002-ad4e005484ec?auto=format&fit=crop&w=800&q=80',
    isFeatured: false,
    tags: ['Valrhona Batons'],
    brewMethod: 'Baked Fresh Hourly',
    calories: 320,
    origin: 'Artisan Oven, In-House',
  },

  // DESSERTS
  {
    name: 'San Sebastián Basque Burnt Cheesecake',
    description: 'Caramelized burnt top with a molten, ultra-creamy custard center made from fresh Philadelphia cream and Tahitian vanilla pods.',
    price: 320,
    category: 'desserts',
    image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=800&q=80',
    isFeatured: true,
    tags: ['Signature Dessert', 'Molten Center'],
    brewMethod: 'High-Heat Caramelization',
    calories: 360,
    origin: 'San Sebastián Recipe',
  },
  {
    name: 'Espresso Bean Tiramisu',
    description: 'Savoiardi ladyfingers soaked in double-pulled Ember & Bean espresso and aged Marsala, layered with whipped mascarpone cream and raw cacao.',
    price: 310,
    category: 'desserts',
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=800&q=80',
    isFeatured: false,
    tags: ['Traditional Italian', 'House Espresso'],
    brewMethod: 'Chilled 24h Set',
    calories: 330,
    origin: 'Veneto Tradition',
  },
  {
    name: 'Valrhona Sea Salt Chocolate Tart',
    description: 'Crisp sable breton pastry shell filled with silky 70% dark chocolate ganache, finished with Maldon sea salt flakes and 24k edible gold.',
    price: 290,
    category: 'desserts',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80',
    isFeatured: false,
    tags: ['Maldon Sea Salt', '24k Gold'],
    brewMethod: 'Hand-Poured Ganache',
    calories: 310,
    origin: 'French Pâtisserie Craft',
  },
];
